import assert from 'node:assert/strict';
import vm from 'node:vm';
import worker from '../worker.js';
const response=await worker.fetch(new Request('https://wo.test/wo-cart.js'),{STRIPE_PUBLISHABLE_KEY:'pk_test'},{});
const script=await response.text();
new vm.Script(script);
const values=new Map([['wo_cart_v1',JSON.stringify([{id:'stock',qty:1}])],['mp-backlist-cart-v1',JSON.stringify([{id:'backlist:book',kind:'backlist',qty:2}])]]);
const context={CART_KEY:'wo_cart_v1',localStorage:{getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},renderCartBadge(){},renderDrawerItems(){},window:{dispatchEvent(){}},Event,alert(){}};
vm.createContext(context);
vm.runInContext(script.slice(script.indexOf('function getCart()'),script.indexOf('// sourceEl is')),context);
vm.runInContext(script.slice(script.indexOf('function removeFromCart('),script.indexOf('function renderCartBadge(')),context);
assert.equal(context.getDisplayCart().length,2);
context.changeCartQty('backlist:book',1);
assert.equal(context.getBookCart()[0].qty,3);
context.setCart([]);
assert.equal(context.getCart().length,0);
assert.equal(context.getBookCart().length,1,'paying regular stock must preserve unpaid books');
context.removeFromCart('backlist:book');
assert.equal(context.getDisplayCart().length,0);
console.log('Combined cart counts, book quantity/removal, and payment isolation verified.');
